server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs de Laravel
  - job_name: laravel
    static_configs:
      - targets:
          - localhost
        labels:
          job: laravel
          __path__: /var/log/laravel/*.log

    pipeline_stages:
      # Parse JSON logs de Laravel
      - json:
          expressions:
            level: level
            message: message
            context: context
            timestamp: datetime

      # Extraer información del contexto
      - json:
          expressions:
            exception: exception
            user_id: user_id
            request_id: request_id
          source: context

      # Establecer el timestamp
      - timestamp:
          source: timestamp
          format: RFC3339

      # Etiquetas adicionales
      - labels:
          level:
          user_id:
          request_id:

      # Output final
      - output:
          source: message

  # Logs de sistema (opcional)
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log
